# Generated by Django 3.1.6 on 2021-04-02 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('ssn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('manager_ssn', models.CharField(max_length=20)),
                ('department_name', models.CharField(max_length=50)),
                ('department_num', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discount_num', models.IntegerField(primary_key=True, serialize=False)),
                ('discount_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('end_date', models.DateTimeField()),
                ('start_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'discount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ssn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=1)),
                ('salary', models.IntegerField()),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_num', models.IntegerField(primary_key=True, serialize=False)),
                ('order_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateField()),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_number', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('release_year', models.DateField()),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('color', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'product_color',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_number', models.IntegerField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'supplier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerDiscountBridge',
            fields=[
                ('discount_num', models.OneToOneField(db_column='discount_num', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mobile_app.discount')),
            ],
            options={
                'db_table': 'customer_discount_bridge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerOrderBridge',
            fields=[
                ('customer_ssn', models.OneToOneField(db_column='customer_ssn', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mobile_app.customer')),
            ],
            options={
                'db_table': 'customer_order_bridge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepartmentLocation',
            fields=[
                ('department_num', models.OneToOneField(db_column='department_num', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mobile_app.department')),
                ('department_location', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'department_location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeOrderBridge',
            fields=[
                ('employee_ssn', models.OneToOneField(db_column='employee_ssn', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mobile_app.employee')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'db_table': 'employee_order_bridge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductOrderBridge',
            fields=[
                ('order_number', models.OneToOneField(db_column='order_number', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mobile_app.order')),
                ('quantity', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'product_order_bridge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierPhone',
            fields=[
                ('supplier_number', models.OneToOneField(db_column='supplier_number', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mobile_app.supplier')),
                ('phone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'supplier_phone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierProductBridge',
            fields=[
                ('supplier_number', models.OneToOneField(db_column='supplier_number', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='mobile_app.supplier')),
                ('phone', models.CharField(max_length=15)),
                ('bought_date', models.DateField()),
                ('supervisor', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'supplier_product_bridge',
                'managed': False,
            },
        ),
    ]
